// web_3.0_react/src/app/page.tsx
'use client'
import { Button } from "@/components/button"
import { NavBar, Container, BackgroundImg, MyText, List, ContainerLinguagens} from "@/styled-components-css/home"
import {useState} from "react"

//rodando do lado do cliente
export default function Home(){
  
  const [apresentacao, setApresentacao] = useState("olá, meu nome é Samuel Jorge Matheus e eu sou Desenvolvedor Front-end,Tecnologias que tenho experiência:")

  const ingl: string = "Hello, my name is Samuel Jorge Matheus and I am a Front-end Developer, Technologies I have experience with:"
  const spa: string = "Hola, mi nombre es Samuel Jorge Matheus y soy Desarrollador Front-end, Tecnologías con las que tengo experiencia:"
  const pt: string = "Olá, meu nome é Samuel Jorge Matheus e eu sou Desenvolvedor Front-end,Tecnologias que tenho experiência:"

  const linguagens = [
    
    {type:"button",Image: "./usa.svg",linguagens:"Inglês",myfunction:()=> setApresentacao(ingl)}, 
    {type:"button",Image: "./brazil.svg",linguagens:"Português",myfunction:()=> setApresentacao(pt)},
    {type:"button",Image: "./spain.svg",linguagens:"Espanhol",myfunction:()=> setApresentacao(spa)},
  ]

  const tecnologias: string[] = [
    "TypeScript",
    "StyledComponents",
    "Html",
    "Java",
    "Css",
    "React",
    "Angular"
  ]//Variável sera constante, contendo array com minhas tecnologias.


  return (
    <Container>
      <NavBar>
      
        <BackgroundImg>
          <img src="./logo.png"/>
        </BackgroundImg>
      </NavBar>
      
      <MyText>
        <p>{apresentacao}</p>
      </MyText>
    <List>
    {tecnologias.map(skills => <li>{skills}</li>) }
    </List>
    <ContainerLinguagens>
      {linguagens.map(ling =>
      
      <Button images={ling.Image} type={ling.type} children={ling.linguagens}onclick={ling.myfunction}/>
      )}
    </ContainerLinguagens>
    
    </Container>
  )
}

// web_3.0_angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.sass']
})

export class AppComponent {

  text = "Olá, meu nome é Samuel Jorge Matheus e eu sou Desenvolvedor Front-end, Tecnologias que tenho experiência:"
  ingl = "Hello, my name is Samuel Jorge Matheus and I am a Front-end Developer, Technologies I have experience with:"
  spa = "Hola, mi nombre es Samuel Jorge Matheus y soy Desarrollador Front-end, Tecnologías con las que tengo experiencia:"
  pt = "Olá, meu nome é Samuel Jorge Matheus e eu sou Desenvolvedor Front-end,Tecnologias que tenho experiência:"

  button = [
    {text: "Portugues", icons:"../assets/brazil.svg", function: ()=> this.text = this.pt},
    {text: "Inglês", icons:"../assets/usa.svg", function: ()=> this.text = this.ingl},
    {text: "Espanhol", icons:"../assets/spain.svg", function: ()=> this.text = this.spa}
  ]
  
  tecnologias = [
    "TypeScript",
    "StyledComponents",
    "Html",
    "Java",
    "Css",
    "React",
    "Angular"
  ]

  
  pageImage = "../assets/brazil.svg"
  Text = this.button[0].text;
  
  teste(): void {
    console.log('Olá, meu anjo');
  }
}

<main>
  <nav class="navbar">
    <div class="boximg"><img src="../assets/stackx.png"/></div>
  </nav >

  <div class="container">
    
    <div class="containertext">
      <p>
        {{text}}
      </p>
    </div>

    <ul class="list">
      <li *ngFor="let text of tecnologias ">
        {{text}}
      </li>

    </ul>

    <div class="button">
      <app-button-page  [buttons]="button" ></app-button-page>
    </div>
  </div>

</main>
